Make sure scan has properly started in scan? check
The previous check was not sufficient since it could
by mocked by Prosopite.resume resulting to unexpected
exceptions:

Prosopite.resume
Prosopite.scan
Prosopite.finish

NoMethodError: undefined method `each' for nil:NilClass
from gems/prosopite-1.1.3/lib/prosopite.rb:84:in `create_notifications'

Credits to @iridakos for raising the issue.